### ISSUE TITLE
hetzner云服务器连不上api.panel.haozi.xyz/api/version/latest

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [DevHaoZi/Panel#2]
hetzner云服务器连不上api.panel.haozi.xyz/api/version/latest
--2022-12-16 17:36:34--  https://api.panel.haozi.xyz/api/version/latest
Resolving api.panel.haozi.xyz (api.panel.haozi.xyz)... 43.248.98.95
Connecting to api.panel.haozi.xyz (api.panel.haozi.xyz)|43.248.98.95|:443... failed: Connection timed out.
Retrying.

--2022-12-16 17:38:46--  (try: 2)  https://api.panel.haozi.xyz/api/version/latest
Connecting to api.panel.haozi.xyz (api.panel.haozi.xyz)|43.248.98.95|:443... failed: Connection timed out.
Retrying.

--2022-12-16 17:40:58--  (try: 3)  https://api.panel.haozi.xyz/api/version/latest
Connecting to api.panel.haozi.xyz (api.panel.haozi.xyz)|43.248.98.95|:443... failed: Connection timed out.
Retrying.

--2022-12-16 17:43:10--  (try: 4)  https://api.panel.haozi.xyz/api/version/latest
Connecting to api.panel.haozi.xyz (api.panel.haozi.xyz)|43.248.98.95|:443... failed: Connection timed out.
Retrying.

--2022-12-16 17:45:26--  (try: 5)  https://api.panel.haozi.xyz/api/version/latest
Connecting to api.panel.haozi.xyz (api.panel.haozi.xyz)|43.248.98.95|:443... failed: Connection timed out.
Retrying.

--2022-12-16 17:47:42--  (try: 6)  https://api.panel.haozi.xyz/api/version/latest
Connecting to api.panel.haozi.xyz (api.panel.haozi.xyz)|43.248.98.95|:443... failed: Connection timed out.
Retrying.

--2022-12-16 17:49:58--  (try: 7)  https://api.panel.haozi.xyz/api/version/latest
Connecting to api.panel.haozi.xyz (api.panel.haozi.xyz)|43.248.98.95|:443... failed: Connection timed out.
Retrying.

--2022-12-16 17:52:14--  (try: 8)  https://api.panel.haozi.xyz/api/version/latest
Connecting to api.panel.haozi.xyz (api.panel.haozi.xyz)|43.248.98.95|:443...

**Comment by DevHaoZi** [comment]
接口的服务器在大陆，连不上可以试试换个时间段\使用代理。

**Comment by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [comment]
> 接口的服务器在大陆，连不上可以试试换个时间段\使用代理。

能不能增加国外服务器，会用这个面板的，没几个是国内服务器吧

**Comment by DevHaoZi** [comment]
> 

缺少服务器赞助

**Comment by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [comment]
> > 
> 
> 缺少服务器赞助

没必要重复造轮子  把文件放在GitHub不就好了

**Comment by DevHaoZi** [comment]
> > 缺少服务器赞助
> 
> 没必要重复造轮子 把文件放在GitHub不就好了

那国内就用不了了
